Add macOS Alpha build configuration for DMG and App Store (#1363)
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201899738287924/task/1210800422873798?focus=true

Description:
This change add build configuration for macOS browser Alpha builds for DMG and App Store.
It also updates notarized and appstore build workflows.

diff --git a/.github/workflows/macos_build_appstore.yml b/.github/workflows/macos_build_appstore.yml
--- a/.github/workflows/macos_build_appstore.yml
+++ b/.github/workflows/macos_build_appstore.yml
@@ -15,6 +15,7 @@ on:
         options:
         - testflight
         - testflight_review
+        - testflight_alpha
         - appstore
       asana-task-url:
         description: "Asana release task URL"
@@ -29,12 +30,21 @@ on:
         type: string
       asana-task-url:
         description: "Asana release task URL"
-        required: true
+        required: false
         type: string
       branch:
         description: "Branch name"
         required: false
         type: string
+      build-number-override:
+        description: "Override build number (for Alpha builds)"
+        required: false
+        type: string
+      skip-notify:
+        description: "Skip Mattermost notification"
+        required: false
+        default: false
+        type: boolean
     secrets:
       SSH_PRIVATE_KEY_FASTLANE_MATCH:
         required: true
@@ -100,7 +110,7 @@ jobs:
       env:
         is-official-release: ${{ (env.destination == 'appstore' || env.destination == 'testflight') && (startsWith(env.branch, 'release') || startsWith(env.branch, 'hotfix')) }}
       run: |
-        if [[ "${{ env.is-official-release }}" == "true" ]]; then
+        if [[ "${{ env.is-official-release }}" == "true" ]] || [[ "${{ env.destination }}" == "testflight_alpha" ]]; then
           upload_to=s3
           echo "upload-to=${upload_to}" >> $GITHUB_OUTPUT
           echo "upload-to=${upload_to}" >> $GITHUB_ENV
@@ -109,6 +119,12 @@ jobs:
     - name: Select Xcode
       uses: ./.github/actions/select-xcode-version
 
+    - name: Override build number for Alpha release
+      if: ${{ env.destination == 'testflight_alpha' && inputs.build-number-override != '' }}
+      run: |
+        echo "Overriding build number to ${{ inputs.build-number-override }}"
+        echo "CURRENT_PROJECT_VERSION = ${{ inputs.build-number-override }}" > Configuration/BuildNumber.xcconfig
+
     - name: Archive and Upload the App
       env:
         APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
@@ -116,21 +132,29 @@ jobs:
         APPLE_API_KEY_ISSUER: ${{ secrets.APPLE_API_KEY_ISSUER }}
         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
       run: |
-        if [ "${{ env.destination }}" == "testflight_review" ]; then
-          app_bundle_name="DuckDuckGo App Store Review"
-          app_dsym_name="DuckDuckGo-AppStore-Review"
-        else
-          app_bundle_name="DuckDuckGo App Store"
-          app_dsym_name="DuckDuckGo-AppStore"
-        fi
+        case "${{ env.destination }}" in
+          testflight_review)
+            app_bundle_name="DuckDuckGo App Store Review"
+            app_dsym_name="DuckDuckGo-AppStore-Review"
+            ;;
+          testflight_alpha)
+            app_bundle_name="DuckDuckGo App Store Alpha"
+            app_dsym_name="DuckDuckGo-AppStore-Alpha"
+            ;;
+          *)
+            app_bundle_name="DuckDuckGo App Store"
+            app_dsym_name="DuckDuckGo-AppStore"
+            ;;
+        esac
 
         bundle exec fastlane release_${{ env.destination }}
         dsym_path="${{ github.workspace }}/macOS/${app_dsym_name}.app.dSYM.zip"
         mv -f "${{ github.workspace }}/macOS/${app_bundle_name}.app.dSYM.zip" "${dsym_path}"
-        version="$(cut -d ' ' -f 3 < Configuration/Version.xcconfig)"
-        build_number="$(cut -d ' ' -f 3 < Configuration/BuildNumber.xcconfig)"
+        version="$(cut -d ' ' -f 3 < Configuration/Version.xcconfig | tr -d '\n')"
+        build_number="$(cut -d ' ' -f 3 < Configuration/BuildNumber.xcconfig | tr -d '\n')"
         echo "dsym-path=${dsym_path}" >> $GITHUB_ENV
         echo "app-version=${version}.${build_number}" >> $GITHUB_ENV
+        echo "app-dsym-name=${app_dsym_name}" >> $GITHUB_ENV
 
     - name: Upload dSYMs artifact
       uses: actions/upload-artifact@v4
@@ -145,7 +169,7 @@ jobs:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
-        DSYM_S3_PATH: s3://${{ vars.DSYM_BUCKET_NAME }}/${{ vars.MACOS_DSYM_BUCKET_PREFIX }}/DuckDuckGo-AppStore-${{ env.app-version }}-dSYM.zip
+        DSYM_S3_PATH: s3://${{ vars.DSYM_BUCKET_NAME }}/${{ vars.MACOS_DSYM_BUCKET_PREFIX }}/${{ env.app-dsym-name }}-${{ env.app-version }}-dSYM.zip
       run: |
         echo "dsym-s3-path=${DSYM_S3_PATH}" >> $GITHUB_OUTPUT
         aws s3 cp ${{ env.dsym-path }} ${{ env.DSYM_S3_PATH }}
@@ -156,6 +180,7 @@ jobs:
         TAG: ${{ env.app-version }}
         WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
         ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
+      if: ${{ env.asana-task-url != '' }}
       run: |
         bundle exec fastlane run asana_log_message \
           task_url:"${{ env.asana-task-url }}" \
@@ -170,7 +195,9 @@ jobs:
         DESTINATION: ${{ env.destination }}
         PLATFORM: macOS
       run: |
-        bundle exec fastlane run mattermost_send_message \
-          mattermost_webhook_url:${{ secrets.MM_WEBHOOK_URL }} \
-          github_handle:${{ github.actor }} \
-          template_name:$([[ "${{ job.status }}" == "success" ]] && echo "public-release-complete" || echo "public-release-failed")
+        if [[ "${{ inputs.skip-notify }}" == "false" ]]; then
+          bundle exec fastlane run mattermost_send_message \
+            mattermost_webhook_url:${{ secrets.MM_WEBHOOK_URL }} \
+            github_handle:${{ github.actor }} \
+            template_name:$([[ "${{ job.status }}" == "success" ]] && echo "public-release-complete" || echo "public-release-failed")
+        fi
