Show diff when pixel linter fails (#1573)
Task/Issue URL:
https://app.asana.com/1/137249556945/project/414709148257752/task/1210957466937460?focus=true
Tech Design URL:
CC:

### Description
Ditto

### Testing Steps
Check CI run from a commit where linting error was introduced: see how
the pixel validation displays a diff of the needed fix

### Impact and Risks
<!-- 
What's the impact on users if something goes wrong?

High: Could affect user privacy, lose user data, break core
functionality
Medium: Could disrupt specific features or user flows
Low: Minor visual changes, small bug fixes, improvement to existing
features
None: Internal tooling, documentation
-->

#### What could go wrong?
<!-- Describe specific scenarios and how you've addressed them -->

### Quality Considerations
<!-- 
Focus on what matters for your changes:
- What edge cases exist?
- How does this affect performance?
- What monitoring have you added?
- What documentation needs updating?
- How does this impact privacy/security?
-->

### Notes to Reviewer
<!-- Anything specific you want reviewers to focus on -->

---
###### Internal references:
[Definition of
Done](https://app.asana.com/0/1202500774821704/1207634633537039/f) |
[Engineering
Expectations](https://app.asana.com/0/59792373528535/199064865822552) |
[Tech Design
Template](https://app.asana.com/0/59792373528535/184709971311943)

diff --git a/.github/workflows/pixel_validation.yml b/.github/workflows/pixel_validation.yml
--- a/.github/workflows/pixel_validation.yml
+++ b/.github/workflows/pixel_validation.yml
@@ -41,7 +41,7 @@ jobs:
         run: npm ci --verbose --include-workspace-root
         working-directory: ${{ matrix.platform }}
       - name: Lint
-        run: npm run pixel-lint
+        run: npm run pixel-lint || (npm run pixel-lint.fix; git diff; echo 'Pixel lint check failed, review diff above or run "npm run pixel-lint.fix"'; exit 1)
         working-directory: ${{ matrix.platform }}        
       - name: Run validation with GitHub user map
         run: npm run validate-defs-without-formatting -- -g ../internal-github-asana-utils/user_map.yml
